### ISSUE TITLE
There are some problems when I compile the source code

### ISSUE THREAD

**Issue by dodiadodia** [Seagate/kinetic-cpp-client#30]
My environment is X86_64. There are 3 problems when I compile the source code:
1. After 'cmake . && make', there is error as follow:
kinetic-cpp-client/src/test/kinetic_cpp_client_test.cc:44:5: error: ‘ShutDownCommandLineFlags’ is not a member of ‘google’
I add a line '#include "gflags/gflags.h' to the kinetic_cpp_client_test.cc

2. Some .a are exported to the vendor/lib64, not in vendor/lib, such as "libgflags.a libglog.a", I am the X86_64. I think it can be fixed simply.

3. In my environment, I need to add -lunwind to the "LIBRARY_DEPENDENCIES" in the CMakeLists.txt, or there are errors:
kinetic-cpp-client-build/vendor/src/glog-build/../glog/src/stacktrace_libunwind-inl.h:65: undefined reference to `_Ux86_64_getcontext'
......

**Comment by liuxian9** [comment]
Hi, dodiadodia:

   I am taking over the C++ Library and I have tested above problems you mentioned in both Ubuntu 14.04 64bit and CentOS 7.1 64bit, It works.  I believe above problems have been fixed and the owner forgot to close this issue.

   Since I am not sure what the exact X86_64 platform you are using, so, I will still keep this issue open for one more week. If the issue still exists, please let me know.  

Thank you.
